# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run setup
    - run: npm run build:gold
    - run: npm run typecheck
    - run: npm test
    - run: npm run lint

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Archive build artifacts
      working-directory: target/
      run: zip -qq -r gamedata.release.zip gamedata/ xrf_build.log README.md

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: gamedata.release.zip
        path: target/gamedata.release.zip
        retention-days: 1

    - name: Update nightly tag
      uses: EndBug/latest-tag@latest
      if: github.ref_name == 'master'
      id: update-nightly-tag
      with:
        ref: nightly

    - name: Publish nightly gamedata build
      if: ${{ steps.update-nightly-tag.outcome == 'success' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload --clobber nightly target/gamedata.release.zip
